### ISSUE TITLE
The nix-singleuser package should create nixbld group

### ISSUE THREAD

**Issue by FrostyX** [juhp/nix-fedora#1]
The `nix-singleuser` package doesn't properly create `nixbld` group.

```
$ docker run -it quay.io/fedora/fedora:40 bash
[root@6d97108304b9 /]# dnf install 'dnf-command(copr)'
[root@6d97108304b9 /]# dnf copr enable petersen/nix
[root@6d97108304b9 /]# dnf install nix-singleuser
[root@6d97108304b9 /]# nix-shell -p hello
warning: the group 'nixbld' specified in 'build-users-group' does not exist
```

The warning is indeed only a warning and the `nix-shell` command finishes successfully. But it can be easily fixed. When the specfile still used `groupadd`, it could be fixed by adding:

```diff
diff --git a/nix.spec b/nix.spec
index 2e43a76..33058c8 100644
--- a/nix.spec
+++ b/nix.spec
@@ -157,6 +157,8 @@ chrpath --delete %{buildroot}%{_bindir}/nix %{buildroot}%{_libdir}/libnixexpr.so
 mkdir -p %{buildroot}/etc/nix
 cp %{SOURCE1} %{SOURCE2} %{buildroot}/etc/nix/

+%pre singleuser
+getent group %{nixbld_group} >/dev/null || groupadd -r %{nixbld_group}

 %pre daemon
 getent group %{nixbld_group} >/dev/null || groupadd -r %{nixbld_group}
```

so probably something similar needs to be done now.

**Comment by juhp** [comment]
Ah I see you are running in a rootful container hm

Hm I was actually deliberately trying to avoid the group in the container, since it is unfriendly for toolbox.

It might be better to install the base `nix` package in a rootful container, even though you don't need the daemon with root.

**Comment by juhp** [comment]
I just tried and the multiuser config installs fine inside a fedora container.

I think singleuser really means for a rootless setup.

I have a sense that running nix as root might be slight frowned upon perhaps, but of course in a rootful container ~less~not much choice

**Comment by juhp** [comment]
nix-singleuser also seems to work okay for me in a fresh Live VM too.

The main reason for it to exist really is that updating it won't change the ownership of /nix/*.
I concede it is a hack really - so if you don't like it you may prefer just to just the main package.
Not sure that nix-singleuser would get through package review either :crying_cat_face:

**Comment by FrostyX** [comment]
Ah sorry, my bad here. I thought this would be representative of what happens on a fresh system but it isn't. I tried the same reproducer in an actual VM and the warning didn't appear.

**Comment by juhp** [comment]
Thanks - no worries - it's tricky stuff

**Comment by juhp** [comment]
(oops mentioned the wrong issue)
